version: 2

updates:
  - package-ecosystem: docker
    directories:
      - /.buildkite
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
