steps:
  - name: ":go: fmt"
    key: test-go-fmt
    command: ".buildkite/steps/check-code-committed.sh"
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: test

  - name: ":hammer: Tests"
    key: tests
    command: "go test ./..."
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          run: test
